/** Synthetic regression data only; these are not extracted financial results. */
import type { ReportData } from './types';

export const alternateReportFixture: ReportData = {
  schemaVersion: 1,
  revision: 'fixture-1',
  mode: 'report',
  report: {
    id: 'alternate-report',
    companyName: '替换数据测试公司（非真实财报）',
    shortName: '测试公司',
    stockCode: 'TEST',
    title: '2024 测试年度报告',
    fiscalPeriod: '2024 年度',
    statementScope: '合并报表',
    currency: '人民币',
    sourceDocumentIds: ['document-other'],
    run: {
      id: 'run-other',
      agentName: 'DB-GPT',
      modelName: 'qwen-plus',
      skillName: 'financial-report-analyzer',
      status: 'running',
      evidenceCoverage: 0,
    },
  },
  documents: [
    {
      id: 'document-other',
      fileName: 'alternate-2024.pdf',
      reportType: '年度报告',
      fiscalPeriod: '2024',
      version: '测试快照',
    },
  ],
  evidence: [
    {
      id: 'source-other',
      sourceDocumentId: 'document-other',
      page: 12,
      snippet: '测试样本：2024 年营业收入 120 元。',
      qualityStatus: 'warning',
    },
  ],
  facts: [
    {
      id: 'value-other',
      metricCode: 'revenue',
      metricName: '营业收入',
      rawValue: '120.00',
      normalizedValue: '120.00',
      displayValue: '120 元',
      unit: '元',
      fiscalPeriod: '2024 年度',
      statementScope: '合并报表',
      evidenceExcerptIds: ['source-other', 'missing-evidence'],
      qualityStatus: 'warning',
    },
  ],
  calculations: [
    {
      id: 'ratio-other',
      name: '测试计算',
      kind: 'deterministic',
      formula: '收入 / 缺失值',
      inputFactIds: ['value-other', 'missing-fact'],
      steps: [],
      result: null,
      displayResult: '不可计算',
      unit: '%',
    },
  ],
  findings: [],
  metrics: [
    {
      id: 'metric-other',
      code: 'revenue',
      name: '营业收入',
      displayValue: '120 元',
      informationKind: 'fact',
      factIds: ['value-other'],
      citationLabel: 'source-other · PDF 12',
    },
  ],
  trends: {
    revenue: [{ year: '2024', metric: '营业收入', value: 120 }],
    cashFlow: [
      { year: '2022', metric: '经营现金流', value: -3 },
      { year: '2024', metric: '经营现金流', value: 0 },
    ],
    profit: [],
    expenses: [],
    financialUnit: '元',
    profitUnit: '元',
  },
  steps: [
    {
      id: 'other-step',
      order: 1,
      type: 'read',
      title: '读取替换样本',
      detail: '测试执行状态',
      status: 'running',
      capability: 'existing',
    },
  ],
  sections: {
    overview: { findingIds: [] },
    profitability: { findingIds: [], calculationIds: ['ratio-other'] },
    cashflow: { findingIds: [] },
    balance: { findingIds: [], factIds: ['missing-fact'] },
  },
  healthMetrics: [{ id: 'missing-ratio', name: '流动比率', displayValue: null }],
  statements: {
    unit: '元',
    periods: [
      { period: '2024 年度', label: '2024' },
      { period: '2022 年度', label: '2022' },
      { period: '2020 年度', label: '2020' },
    ],
    rows: [{ id: 'other-row', name: '营业收入', factIds: ['value-other', 'missing-fact'] }],
  },
  artifacts: [],
  agent: {
    userQuery: '读取替换测试报告',
    summary: '资料待核对',
    groups: [{ id: 'other-group', title: '读取资料', content: '测试任务', stepIds: ['other-step'] }],
  },
};

export const emptyReportFixture: ReportData = {
  ...alternateReportFixture,
  revision: 'empty-1',
  documents: [],
  evidence: [],
  facts: [],
  calculations: [],
  findings: [],
  metrics: [],
  steps: [],
  trends: { revenue: [], cashFlow: [], profit: [], expenses: [], financialUnit: '元', profitUnit: '元' },
  sections: {
    overview: { findingIds: [] },
    profitability: { findingIds: [] },
    cashflow: { findingIds: [] },
    balance: { findingIds: [] },
  },
  healthMetrics: [],
  statements: { unit: '元', periods: [], rows: [] },
  agent: { userQuery: '', summary: '', groups: [] },
};
